name: Build And Deploy
on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-backend:
    name: Build the backend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        build-root-directory: backend
        arguments: build
    - name: Build docker image
      uses: docker/build-push-action@v5.0.0
      with:
        tags: carbon-criters-backend:latest
